# Generated by Django 2.1.2 on 2018-10-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_auto_20181020_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='grupo',
            new_name='grupo_destino',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidentes.Equipos'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='grupo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo',
            field=models.ManyToManyField(to='incidentes.Grupo'),
        ),
    ]
