# Generated by Django 2.1.2 on 2018-10-30 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0008_auto_20181024_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='nombre',
            new_name='ubicacion',
        ),
        migrations.AddField(
            model_name='ticket',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editado', to='incidentes.Usuario'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
