# Generated by Django 2.1.2 on 2018-10-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0009_auto_20181030_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='editado_por',
        ),
        migrations.AddField(
            model_name='ticket',
            name='editado_por',
            field=models.ManyToManyField(related_name='nombre2', to='incidentes.Usuario'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario',
            field=models.ManyToManyField(to='incidentes.Usuario'),
        ),
    ]
