# Generated by Django 2.1.2 on 2018-10-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0010_auto_20181030_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='editado_por',
            field=models.ManyToManyField(blank=True, related_name='nombre2', to='incidentes.Usuario'),
        ),
    ]
