# Generated by Django 2.1.2 on 2018-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0012_auto_20181030_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='editado_por',
            field=models.ManyToManyField(blank=True, default='', related_name='nombre2', to='incidentes.Usuario'),
        ),
    ]
