# Generated by Django 2.1.2 on 2018-11-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='editado_por',
            field=models.ManyToManyField(blank=True, null=True, related_name='nombre2', to='incidentes.Usuario'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='grupo_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidentes.Grupo'),
        ),
    ]
