# Generated by Django 2.1.2 on 2018-11-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_auto_20181120_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='editado_por',
        ),
        migrations.AddField(
            model_name='ticket',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombre2', to='incidentes.Usuario'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidentes.Usuario'),
        ),
    ]
